### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by Mafanshiva** [noob-hackers/mrphish#20]
Tool is offline when it's gonna online

**Comment by MADmeow9** [comment]
A help, 

____[online]                                  
 |                                              
[+] STARTING DATA SERVER ....
 |                                              
[+] STARTING DEPLOY SERVER....
 |
[+] DEPLOY LINK STATUS [ERROR]                   |
[+]  PLEASE USE HOTPOST OR SPEED DATA OR USE AUTH TOKEN
 |                                              [+]  HOLD CTRL + C OR USE VOLUME DOWN + C TO STOP


Can u able to solve this pls, trying to connect to any service, I'm getting this error, hotspot is on, attached the ngrok token while installing, still this problem.. if possible or if you know can reply thanks..

**Comment by kanishkthamman** [comment]
pls refer #24
