### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by thib6622** [noob-hackers/mrphish#24]
![Screenshot_20210915-000708_Termux](https://user-images.githubusercontent.com/84886820/133340585-d6a78e4b-72dd-41b1-9261-b8dc282ae2c5.jpg)
someone know how to solve this ?

**Comment by oporadokrl** [comment]
Hello, you need to enable your hotspot on the status bar in your phone to solve this error or get your personal auth token with ngrok.

**Comment by Ingibator** [comment]
> Hello, you need to enable your hotspot on the status bar in your phone to solve this error or get your personal auth token with ngrok.

Hi! I did it all. And I have a token, but it didn't working... Can you help me?

**Comment by vladknowsbetter** [comment]
> Hello, you need to enable your hotspot on the status bar in your phone to solve this error or get your personal auth token with ngrok.

How to get the personal auth token

**Comment by oporadokrl** [comment]
> > Hello, you need to enable your hotspot on the status bar in your phone to solve this error or get your personal auth token with ngrok.
> 
> Hi! I did it all. And I have a token, but it didn't working... Can you help me?

Try executing ngrok directly from command line or open ngrok local page with 127.0.0.1 in your browser with port 3333, 8080 or 8000

**Comment by oporadokrl** [comment]
> > Hello, you need to enable your hotspot on the status bar in your phone to solve this error or get your personal auth token with ngrok.
> 
> How to get the personal auth token

Enter in the official ngrok website, register and in your dashboard will appear your auth token, after that you just follow the instructions normaly.

**Comment by oporadokrl** [comment]
renember: ngrok have different arch versions, for use with termux you may need a ngrok ARMv7 version binary.
