### ISSUE TITLE
deploy link stauts(error)

### ISSUE THREAD

**Issue by ullasmc29** [noob-hackers/mrphish#25]
at the final it is showing error what was the problem

**Comment by vladknowsbetter** [comment]
Same for me
It says "PLEASE USE HOTPOST OR SPEED DATA OR USE AUTH TOKEN"
I have tried using hotspot ... my net speed is good . Help

**Comment by vishaldutia** [comment]
I have the same problem

**Comment by Adilet002** [comment]
How
