### ISSUE TITLE
Authorization Code

### ISSUE THREAD

**Issue by robstars89** [noob-hackers/mrphish#27]
NGROK AUTHORIZATION CODE? What is the code I can't seem to find it?

**Comment by kanishkthamman** [comment]
NGROK AUTHORIZATION CODE is like a api key kinda..
you can get it from doing the following...
step 1:- go here and login/Sign Up up https://dashboard.ngrok.com/signup
then 
step 2:- you will get the auth token i will be given like this 
in the home page which link is https://dashboard.ngrok.com/get-started/setup

./ngrok authtoken "your auth token"
hope this fixes your prob
