### ISSUE TITLE
Auth Token not working

### ISSUE THREAD

**Issue by TheETR** [noob-hackers/mrphish#28]
I sign in on ngrok.com and I put my auth code using "cd ~/mrphish/core/ && ./ngrok authtoken 'My Auth Token'" 

But I cant use it... Can someone help me?
![Screenshot_20211227-193624_Termux](https://user-images.githubusercontent.com/83076246/147490802-e9432f2f-5cf6-4058-9c1f-b2f373144b2b.jpg)

[I also try nearly 40 options (also with otp, without otp)]

**Comment by adhaushivam** [comment]
Same with me
