### ISSUE TITLE
Link wont appear

### ISSUE THREAD

**Issue by veemoC3** [noob-hackers/mrphish#5]
Hi,the link wont appear,i dont know why,version is the latest and phishing page i tried to use was instagram
Hope you fix this![Screenshot_20201022-141719_Termux.jpg](https://user-images.githubusercontent.com/73198803/96870611-72834e80-1471-11eb-9819-5a72f94e7632.jpg)

**Comment by noob-hackers** [comment]
Thanks for feedback i will fox it soon
