### ISSUE TITLE
How to install on kali nethunter (terminal)

### ISSUE THREAD

**Issue by kennye88** [noob-hackers/mrphish#6]
Hello, your installation instructions are for termux .. Can you please write how to install "mrphish" in the terminal kali nethunter (kali linux)?

**Comment by djbhavesh** [comment]
Simply copy and paste this code to Termux command line to install Kali Linux:

pkg install wget proot -y && wget https://raw.githubusercontent.com/MasterDevX/KaliTermux/master/InstallKali.sh && bash InstallKali.sh

After installing run ./start-kali.sh to launch Kali.

**Comment by kennye88** [comment]
hello, you do not quite understand me, I do not need to install kali
... I already have Kali nethunter installed, and I use the kali
terminal, not termux. So I want to know how to install mrphish in
terminal


чт, 29 окт. 2020 г., 16:48 djbhavesh <notifications@github.com>:

**Comment by noob-hackers** [comment]
sry kenny we will try to update that in future
